# GitLab CI/CD Pipeline Configuration file
# https://docs.gitlab.com/ee/ci/yaml/
---
# environment variables - also set in every service for a job
# NB: setting PGHOST will cause the postgres service to fail
variables:
  SECRET_KEY: static secret key
  SQLALCHEMY_DATABASE_TEST_URI: postgresql://postgres:${POSTGRES_PASSWORD}@postgres/${POSTGRES_DB}
  REDIS_URL: redis://redis:6379/0
  POSTGRES_DB: portaldb
  POSTGRES_PASSWORD: wplatrop
stages:
  - test
  - deploy

before_script:
  - pip install tox


# test templates
.test_template: &test_definition
  # track debian stable version of python3
  image: python:3.7
  script: tox
  stage: test

.unit_test_template: &unit_test_definition
  <<: *test_definition
  services:
    - postgres:13
    - redis:latest


# test jobs
unit_tests:
  variables:
    TOXENV: py3
  <<: *unit_test_definition

unit_tests_celery_background:
  variables:
    TOXENV: celery_background
  <<: *unit_test_definition

unit_tests_deadlocks:
  variables:
    TOXENV: deadlocks
  <<: *unit_test_definition

docgen_test:
  variables:
    TOXENV: docs
  <<: *test_definition

i18n_test_eproms:
  variables:
    TOXENV: translations
    PERSISTENCE_DIR: eproms
  <<: *unit_test_definition

i18n_test_tnusa:
  variables:
    TOXENV: translations
    PERSISTENCE_DIR: gil
  <<: *unit_test_definition


# deploy templates
.i18n_upload_template: &i18n_upload_definition
  stage: deploy
  # TODO re-enable/remove when future of Smartling integration more certain
  # disable Smartling string uploads
  when: manual
  script:
    - tox
    # reuse tox virtual environment to also upload translations
    - FLASK_APP=manage.py .tox/${TOXENV}/bin/python -m flask translation-upload
  # only upload translations from develop branch
  only:
    refs: [develop]

# deploy jobs
i18n_upload_eproms:
  <<: *unit_test_definition
  <<: *i18n_upload_definition
  variables:
    TOXENV: translations
    PERSISTENCE_DIR: eproms

i18n_upload_tnusa:
  <<: *unit_test_definition
  <<: *i18n_upload_definition
  variables:
    TOXENV: translations
    PERSISTENCE_DIR: gil
